### ISSUE TITLE
0.0.14 natchez-log artifact is empty

### ISSUE THREAD

**Issue by keirlawson** [tpolecat/natchez#208]
Whilst 0.0.13 contains the expected `Log` object when downloaded from Maven, the jar for 0.0.14 contains no class files at all.

**Comment by keirlawson** [comment]
Ah looks like there is already a PR for this - https://github.com/tpolecat/natchez/pull/196

**Comment by pauljamescleary** [comment]
@keirlawson This was merged and should be available with the release 0.0.19
