### ISSUE TITLE
Open tracing Tags

### ISSUE THREAD

**Issue by tbrown1979** [tpolecat/natchez#7]
In attemping to add an http4s module I found that adding the tags from OpenTracing could be useful for defining the tag names for http method, status code, etc...

These are defined here: https://github.com/opentracing/specification/blob/master/semantic_conventions.md

I think it would make sense for these to go in `core`, but let me know. I'm more than willing to get this added to the project 😄

**Comment by tpolecat** [comment]
That makes sense. You can put them in core for now. Note that I just rewrote basically the whole library, so be sure you're up to date.

Also note that they just that OpenTracing + OpenCensus are merging and becoming OpenTelemetry, so I imagine there will be a lot of changes. I'm trying to ignore all that and just work with Honeycomb for now.
