### ISSUE TITLE
Idea: Allow treating the span as a resource in Trace

### ISSUE THREAD

**Issue by kubukoz** [tpolecat/natchez#73]
Currently, the Trace API has this:

```scala
def span[A](name: String)(k: F[A]): F[A]
```

I believe it would also be beneficial to have a variant that returns a resource:

```scala
trait Trace[F[_]] {
  def spanR(name: String): Resource[F, Span[F]]
}
```

Why? For example, for composing it with other resources...

```scala
Trace[F].spanR("my-resource") *> someResource
```

This would track the lifetime of the resource (and set the span in the composed resource's `use` too).

Also, you could use it with streams:

```scala
fs2.Stream.resource(Trace[F].spanR("my-resource")) *> someStream
```

This span would also last as long as the stream, and propagate to every effect in the stream.

I managed to get this with some hackery (Resource of Kleisli doesn't really look that good, but it works: https://github.com/tpolecat/natchez/pull/72

**Comment by tpolecat** [comment]
Yep I have been thinking about something like this. Thanks, I'll have a look at your PR.

**Comment by kubukoz** [comment]
Closing with explanation in #72
