### ISSUE TITLE
Add headers for jeager, zipkin, open-tracing, honeycomb, etc..

### ISSUE THREAD

**Issue by tbrown1979** [tpolecat/natchez#9]
These will be necessary to make the http4s middlewares. We have to know which headers to extract and pass on. I'm not really sure where these should live atm.

**Comment by tpolecat** [comment]
The Natchez API defines `Span#kernel` and `EntryPoint#continue` for this purpose. Look at the Honeycomb and Jaeger implementations (the latter relies on the OpenTracing API to do this). So I don't think we need these headers defined anywhere; the OpenTracing implementations already know them.

**Comment by tbrown1979** [comment]
@tpolecat The use-case I'm referring to here is having a server automatically pull headers from an incoming request and use `EntryPoint#continue`. To do that I have to be able to create a function of 
`Http4sRequest => Kernel`, but to do that we'll need to know which headers are being used. I could be mistaken here so please let me know if I'm missing something. 😄

**Comment by tpolecat** [comment]
The idea is that you pass all the headers in, and the implementation pulls out the ones it wants. So we just need to go from http4s `Headers` to `Map[String, String]` to `Kernel` and it should work without us having to know which headers a particular implementation cares about.

**Comment by tbrown1979** [comment]
Ohhhh, yeah that makes sense. Okay, thanks for explaining that 😄
